apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlsrouter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlsrouter
  template:
    metadata:
      name: tlsrouter
      labels:
        app: tlsrouter
    spec:
      containers:
        - image: 'hub.docker.com/michielkalkman/tlsrouter:1.0.0'
          imagePullPolicy: IfNotPresent
          name: tlsrouter
          args:
          - '/bin/tlsrouter'
          - '-conf'
          - '/etc/tlsrouter/tlsrouter.conf'
          - '-listen'
          - ':8443'
          ports:
            - containerPort: 8443
              protocol: TCP
          resources: {}
          securityContext:
            capabilities:
              drop:
              - all
          volumeMounts:
            - mountPath: /etc/tlsrouter
              name: tlsrouter-config
      volumes:
        - configMap:
            defaultMode: 420
            name: tlsrouter-config
          name: tlsrouter-config

