apiVersion: v1
kind: Service
metadata:
  name: tlsrouter-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
  selector:
    app: tlsrouter
  type: LoadBalancer

